import random

names = [
    "Navneet Saunee",
    "Akash Suthar",
    "Vineet Yadav",
    "Sunny Yadav",
    "Eshan Gupta",
    "Devanshi Jani",
    "Pujan Makadia",
    "Dhruvi Makati",
    "Hariom Suryvanshi",
    "Dhruv Surani",
    "Bhumi Lakum",
    "Shivani Agrawal",
    "Aalap Jethwa",
    "Chetan Vashisth",
    "Jaykishan Brahmakshatriya",
    "Yash Ramani",
    "Mitul Rathod",
    "Yash Vinda",
    "Dhaval Karen",
    "Kairavi Shah",
    "Hiral Talsaniya",
    "Harsh Soni",
    "Kuldeep Patel",
    "Prachi Acharya",
    "Sharvik Patel",
    "Prarthana Maheta",
    "Hanisha Jain",
    "Tanvi Rupareliya",
    "Shashank Gupta",
    "Nikunj Panchal",
    "Chirag Kanzariya",
    "Subham Polpagedar",
    "Tarun Advani",
    "Ashfand Shaikh",
    "Jay Patel",
    "Mitang Shah",
    "Siddharth Rakholiya",
]
print(random.choice(names))
