# Generated by Django 4.1.5 on 2023-01-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cache_view', '0002_amenity_place_restaurant_waiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
