# Generated by Django 4.1.5 on 2023-01-05 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cache_view', '0003_alter_place_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiter',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiters', to='cache_view.restaurant'),
        ),
    ]
