# Generated by Django 4.1.5 on 2023-01-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cache_view', '0004_alter_waiter_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiter',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
